# Generated by Django 2.2.2 on 2019-06-13 17:54

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Главная страница', 'verbose_name_plural': 'Главная страница'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=models.CharField(blank=True, default='Заголовок', max_length=50, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_intro',
            field=wagtail.core.fields.RichTextField(blank=True, default='Заголовок', max_length=50, verbose_name='Текст под заголовком'),
        ),
    ]
