# Generated by Django 2.2.2 on 2019-06-13 17:55

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190613_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='text_intro',
            field=wagtail.core.fields.RichTextField(blank=True, default='', max_length=50, verbose_name='Текст под заголовком'),
        ),
    ]
