# Generated by Django 2.2.2 on 2019-06-13 18:00

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190613_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='text_contacts',
            field=wagtail.core.fields.RichTextField(blank=True, default='', max_length=50, verbose_name='Текст под заголовком а контактах'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_contacts',
            field=models.CharField(blank=True, default='Наши контакты', max_length=50, verbose_name='Подзаголовок Контактов'),
        ),
    ]
