# Generated by Django 2.2.2 on 2019-06-18 06:53

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='text_intro',
            field=wagtail.core.fields.RichTextField(blank=True, default='', max_length=250, verbose_name='Текст под заголовком'),
        ),
    ]
