# Generated by Django 2.2.2 on 2019-06-18 11:54

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='text_contacts',
            field=wagtail.core.fields.RichTextField(blank=True, default='', max_length=250, verbose_name='Текст под заголовком а контактах'),
        ),
    ]
