# Generated by Django 2.2.2 on 2019-06-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsettings',
            name='email',
            field=models.CharField(max_length=25, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='phone',
            field=models.CharField(max_length=25, verbose_name='Телефон'),
        ),
    ]
